spring:
  application:
    name:  strack-user-auth
  profiles:
    active: bala
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:http://localhost:8888"