server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: 
            - file://C:/Users/balap/OneDrive/Documents/Code/spring/config-server/src/main/resources/config-repo
            - classpath:/config-repo
            - optional:file:./config-repo

# spring:
#   profiles:
#     active: native
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/simplytrack
  #   username: postgres
  #   password: 
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #       format_sql: true
  #   show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"